// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usermgr/v1/micro/usermgr.proto

package usermgr

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/Ankr-network/dccn-common/protos/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpdateAttributesRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAttributesRequest) Reset()         { *m = UpdateAttributesRequest{} }
func (m *UpdateAttributesRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAttributesRequest) ProtoMessage()    {}
func (*UpdateAttributesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgr_449136a1c6bcee8e, []int{0}
}
func (m *UpdateAttributesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAttributesRequest.Unmarshal(m, b)
}
func (m *UpdateAttributesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAttributesRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateAttributesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAttributesRequest.Merge(dst, src)
}
func (m *UpdateAttributesRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAttributesRequest.Size(m)
}
func (m *UpdateAttributesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAttributesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAttributesRequest proto.InternalMessageInfo

func (m *UpdateAttributesRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type ChangePasswordRequest struct {
	OldPassword          string   `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgr_449136a1c6bcee8e, []int{1}
}
func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (dst *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(dst, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

type ChangeEmailRequest struct {
	NewEmail             string   `protobuf:"bytes,1,opt,name=new_email,json=newEmail,proto3" json:"new_email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeEmailRequest) Reset()         { *m = ChangeEmailRequest{} }
func (m *ChangeEmailRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeEmailRequest) ProtoMessage()    {}
func (*ChangeEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgr_449136a1c6bcee8e, []int{2}
}
func (m *ChangeEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeEmailRequest.Unmarshal(m, b)
}
func (m *ChangeEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeEmailRequest.Marshal(b, m, deterministic)
}
func (dst *ChangeEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeEmailRequest.Merge(dst, src)
}
func (m *ChangeEmailRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeEmailRequest.Size(m)
}
func (m *ChangeEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeEmailRequest proto.InternalMessageInfo

func (m *ChangeEmailRequest) GetNewEmail() string {
	if m != nil {
		return m.NewEmail
	}
	return ""
}

type VerifyEmailRequest struct {
	NewEmail             string   `protobuf:"bytes,1,opt,name=new_email,json=newEmail,proto3" json:"new_email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyEmailRequest) Reset()         { *m = VerifyEmailRequest{} }
func (m *VerifyEmailRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyEmailRequest) ProtoMessage()    {}
func (*VerifyEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgr_449136a1c6bcee8e, []int{3}
}
func (m *VerifyEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyEmailRequest.Unmarshal(m, b)
}
func (m *VerifyEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyEmailRequest.Marshal(b, m, deterministic)
}
func (dst *VerifyEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyEmailRequest.Merge(dst, src)
}
func (m *VerifyEmailRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyEmailRequest.Size(m)
}
func (m *VerifyEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyEmailRequest proto.InternalMessageInfo

func (m *VerifyEmailRequest) GetNewEmail() string {
	if m != nil {
		return m.NewEmail
	}
	return ""
}

type User struct {
	// id self-increase, de
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name should be unique
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// email user's email, unique.
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// password string
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	// balance user's balance in account
	Balance int32 `protobuf:"varint,5,opt,name=balance,proto3" json:"balance,omitempty"`
	// is_deleted user's status
	IsDeleted bool `protobuf:"varint,6,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	// token jwt token string
	Token string `protobuf:"bytes,7,opt,name=token,proto3" json:"token,omitempty"`
	// block chains public keys
	PublicKeys []string `protobuf:"bytes,8,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	// is_activation register if confirmed
	IsActivation bool `protobuf:"varint,9,opt,name=is_activation,json=isActivation,proto3" json:"is_activation,omitempty"`
	// user create date
	CreationDate         uint64   `protobuf:"varint,10,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgr_449136a1c6bcee8e, []int{4}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetBalance() int32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *User) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

func (m *User) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *User) GetPublicKeys() []string {
	if m != nil {
		return m.PublicKeys
	}
	return nil
}

func (m *User) GetIsActivation() bool {
	if m != nil {
		return m.IsActivation
	}
	return false
}

func (m *User) GetCreationDate() uint64 {
	if m != nil {
		return m.CreationDate
	}
	return 0
}

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgr_449136a1c6bcee8e, []int{5}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Token                string        `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User                 *User         `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Error                *common.Error `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgr_449136a1c6bcee8e, []int{6}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (dst *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(dst, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LoginResponse) GetError() *common.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type LogoutRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgr_449136a1c6bcee8e, []int{7}
}
func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (dst *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(dst, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type AskResetPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AskResetPasswordRequest) Reset()         { *m = AskResetPasswordRequest{} }
func (m *AskResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*AskResetPasswordRequest) ProtoMessage()    {}
func (*AskResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgr_449136a1c6bcee8e, []int{8}
}
func (m *AskResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskResetPasswordRequest.Unmarshal(m, b)
}
func (m *AskResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskResetPasswordRequest.Marshal(b, m, deterministic)
}
func (dst *AskResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskResetPasswordRequest.Merge(dst, src)
}
func (m *AskResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_AskResetPasswordRequest.Size(m)
}
func (m *AskResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AskResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AskResetPasswordRequest proto.InternalMessageInfo

func (m *AskResetPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ResetPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRequest) Reset()         { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()    {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgr_449136a1c6bcee8e, []int{9}
}
func (m *ResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRequest.Unmarshal(m, b)
}
func (m *ResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRequest.Marshal(b, m, deterministic)
}
func (dst *ResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRequest.Merge(dst, src)
}
func (m *ResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRequest.Size(m)
}
func (m *ResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRequest proto.InternalMessageInfo

func (m *ResetPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ResetPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ResetPasswordRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ActivateRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateRequest) Reset()         { *m = ActivateRequest{} }
func (m *ActivateRequest) String() string { return proto.CompactTextString(m) }
func (*ActivateRequest) ProtoMessage()    {}
func (*ActivateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgr_449136a1c6bcee8e, []int{10}
}
func (m *ActivateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateRequest.Unmarshal(m, b)
}
func (m *ActivateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateRequest.Marshal(b, m, deterministic)
}
func (dst *ActivateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateRequest.Merge(dst, src)
}
func (m *ActivateRequest) XXX_Size() int {
	return xxx_messageInfo_ActivateRequest.Size(m)
}
func (m *ActivateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateRequest proto.InternalMessageInfo

func (m *ActivateRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgr_449136a1c6bcee8e, []int{11}
}
func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (dst *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(dst, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type NewTokenResponse struct {
	Token                string        `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Error                *common.Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NewTokenResponse) Reset()         { *m = NewTokenResponse{} }
func (m *NewTokenResponse) String() string { return proto.CompactTextString(m) }
func (*NewTokenResponse) ProtoMessage()    {}
func (*NewTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgr_449136a1c6bcee8e, []int{12}
}
func (m *NewTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTokenResponse.Unmarshal(m, b)
}
func (m *NewTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTokenResponse.Marshal(b, m, deterministic)
}
func (dst *NewTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTokenResponse.Merge(dst, src)
}
func (m *NewTokenResponse) XXX_Size() int {
	return xxx_messageInfo_NewTokenResponse.Size(m)
}
func (m *NewTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewTokenResponse proto.InternalMessageInfo

func (m *NewTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *NewTokenResponse) GetError() *common.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*UpdateAttributesRequest)(nil), "usermgr.UpdateAttributesRequest")
	proto.RegisterType((*ChangePasswordRequest)(nil), "usermgr.ChangePasswordRequest")
	proto.RegisterType((*ChangeEmailRequest)(nil), "usermgr.ChangeEmailRequest")
	proto.RegisterType((*VerifyEmailRequest)(nil), "usermgr.VerifyEmailRequest")
	proto.RegisterType((*User)(nil), "usermgr.User")
	proto.RegisterType((*LoginRequest)(nil), "usermgr.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "usermgr.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "usermgr.LogoutRequest")
	proto.RegisterType((*AskResetPasswordRequest)(nil), "usermgr.AskResetPasswordRequest")
	proto.RegisterType((*ResetPasswordRequest)(nil), "usermgr.ResetPasswordRequest")
	proto.RegisterType((*ActivateRequest)(nil), "usermgr.ActivateRequest")
	proto.RegisterType((*Token)(nil), "usermgr.Token")
	proto.RegisterType((*NewTokenResponse)(nil), "usermgr.NewTokenResponse")
}

func init() {
	proto.RegisterFile("usermgr/v1/micro/usermgr.proto", fileDescriptor_usermgr_449136a1c6bcee8e)
}

var fileDescriptor_usermgr_449136a1c6bcee8e = []byte{
	// 716 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xdd, 0x53, 0xd3, 0x40,
	0x10, 0xa7, 0xa5, 0x9f, 0xdb, 0x52, 0x98, 0x03, 0x24, 0x96, 0x01, 0x4b, 0x7c, 0xb0, 0xbe, 0xb4,
	0x82, 0x8a, 0x8e, 0x0f, 0x8e, 0x1d, 0x3e, 0x1c, 0x06, 0x65, 0x9c, 0x28, 0x3e, 0x9a, 0x49, 0x9b,
	0xa5, 0xdc, 0xd0, 0xe4, 0xea, 0xdd, 0x95, 0x0e, 0x7f, 0x83, 0xef, 0xfe, 0xbd, 0x4e, 0xee, 0x92,
	0x34, 0x2d, 0x0d, 0x1f, 0x3e, 0x25, 0xbb, 0xb7, 0xfb, 0xdb, 0xdb, 0xdf, 0x6f, 0x6f, 0x61, 0x7b,
	0x24, 0x90, 0x7b, 0x7d, 0xde, 0xbe, 0xde, 0x6d, 0x7b, 0xb4, 0xc7, 0x59, 0x3b, 0x74, 0xb4, 0x86,
	0x9c, 0x49, 0x46, 0x8a, 0xa1, 0x59, 0x5f, 0xed, 0x31, 0xcf, 0x63, 0x7e, 0x5b, 0x7f, 0xf4, 0xa9,
	0xb9, 0x0f, 0x1b, 0xe7, 0x43, 0xd7, 0x91, 0xd8, 0x91, 0x92, 0xd3, 0xee, 0x48, 0xa2, 0xb0, 0xf0,
	0xf7, 0x08, 0x85, 0x24, 0x9b, 0x50, 0x0e, 0x52, 0x6d, 0xdf, 0xf1, 0xd0, 0xc8, 0x34, 0x32, 0xcd,
	0xb2, 0x55, 0x0a, 0x1c, 0x67, 0x8e, 0x87, 0xe6, 0x07, 0x58, 0x3f, 0xb8, 0x74, 0xfc, 0x3e, 0x7e,
	0x73, 0x84, 0x18, 0x33, 0xee, 0x46, 0x59, 0x3b, 0x50, 0x65, 0x03, 0xd7, 0x1e, 0x86, 0xee, 0x30,
	0xb1, 0xc2, 0x06, 0x6e, 0x14, 0x69, 0xee, 0x02, 0xd1, 0xb9, 0x47, 0x9e, 0x43, 0x07, 0x89, 0x72,
	0x3e, 0x8e, 0x6d, 0x0c, 0x7c, 0x51, 0x39, 0x1f, 0xc7, 0x2a, 0x26, 0x48, 0xf9, 0x89, 0x9c, 0x5e,
	0xdc, 0x3c, 0x3c, 0xe5, 0x6f, 0x16, 0x72, 0xe7, 0x02, 0x39, 0xa9, 0x41, 0x96, 0x46, 0xf7, 0xc8,
	0x52, 0x97, 0x10, 0xc8, 0xa9, 0x96, 0xb2, 0xca, 0xa3, 0xfe, 0xc9, 0x1a, 0xe4, 0x35, 0xca, 0xa2,
	0x72, 0x6a, 0x83, 0xd4, 0xa1, 0x14, 0xf7, 0x91, 0xd3, 0xf0, 0x91, 0x4d, 0x0c, 0x28, 0x76, 0x9d,
	0x81, 0xe3, 0xf7, 0xd0, 0xc8, 0x37, 0x32, 0xcd, 0xbc, 0x15, 0x99, 0x64, 0x0b, 0x80, 0x0a, 0xdb,
	0xc5, 0x01, 0x4a, 0x74, 0x8d, 0x42, 0x23, 0xd3, 0x2c, 0x59, 0x65, 0x2a, 0x0e, 0xb5, 0x23, 0x28,
	0x25, 0xd9, 0x15, 0xfa, 0x46, 0x51, 0x97, 0x52, 0x06, 0x79, 0x06, 0x95, 0xe1, 0xa8, 0x3b, 0xa0,
	0x3d, 0xfb, 0x0a, 0x6f, 0x84, 0x51, 0x6a, 0x2c, 0x36, 0xcb, 0x16, 0x68, 0xd7, 0x29, 0xde, 0x08,
	0xf2, 0x1c, 0x96, 0xa8, 0xb0, 0x9d, 0x9e, 0xa4, 0xd7, 0x8e, 0xa4, 0xcc, 0x37, 0xca, 0x0a, 0xb8,
	0x4a, 0x45, 0x27, 0xf6, 0x05, 0x41, 0x3d, 0x8e, 0xea, 0xdf, 0x0e, 0x44, 0x35, 0xa0, 0x91, 0x69,
	0xe6, 0xac, 0x6a, 0xe4, 0x3c, 0x74, 0x24, 0x9a, 0x9f, 0xa0, 0xfa, 0x85, 0xf5, 0xa9, 0x1f, 0xb1,
	0x18, 0xf7, 0x9e, 0x49, 0xeb, 0x3d, 0x3b, 0xdd, 0xbb, 0x29, 0x60, 0x29, 0x44, 0x10, 0x43, 0xe6,
	0x0b, 0x9c, 0xf4, 0x94, 0x49, 0xf6, 0xb4, 0x03, 0xb9, 0x60, 0x5e, 0x54, 0x7a, 0x65, 0x6f, 0xa9,
	0x15, 0xcd, 0x65, 0xa0, 0x8a, 0xa5, 0x8e, 0xc8, 0x4b, 0xc8, 0x23, 0xe7, 0x8c, 0x2b, 0xde, 0x2b,
	0x7b, 0xab, 0xad, 0xe4, 0x70, 0xb6, 0x8e, 0x82, 0x23, 0x4b, 0x47, 0x98, 0x4d, 0x55, 0x94, 0x8d,
	0x64, 0x74, 0xef, 0x0d, 0x50, 0xa3, 0x6d, 0xc7, 0xe2, 0x16, 0x02, 0xf3, 0xc4, 0x35, 0xdb, 0xb0,
	0xd1, 0x11, 0x57, 0x16, 0x0a, 0x94, 0xb3, 0xd3, 0x39, 0xb7, 0x57, 0xf3, 0x17, 0xac, 0x3d, 0x3c,
	0xfa, 0x2e, 0x66, 0x26, 0x44, 0x2c, 0x26, 0x88, 0x30, 0x5f, 0xc0, 0x72, 0x28, 0x12, 0x26, 0xa0,
	0x6f, 0x33, 0x66, 0x6e, 0x41, 0xfe, 0x87, 0xa2, 0x6e, 0xfe, 0xf1, 0x77, 0x58, 0x39, 0xc3, 0xb1,
	0x8a, 0xb8, 0x87, 0xfa, 0x98, 0xd7, 0xec, 0x7d, 0xbc, 0xee, 0xfd, 0x29, 0x42, 0x31, 0x50, 0xe4,
	0x6b, 0x9f, 0x93, 0x57, 0x50, 0xb2, 0xb0, 0x4f, 0x85, 0x44, 0x4e, 0xa6, 0xf5, 0xaa, 0xcf, 0x83,
	0x30, 0x17, 0xc8, 0x7b, 0xc8, 0xab, 0x51, 0x20, 0xeb, 0x71, 0x78, 0x72, 0xb8, 0xea, 0x4f, 0x66,
	0xdd, 0xfa, 0xda, 0xe6, 0x02, 0x79, 0x07, 0x05, 0xad, 0x27, 0x99, 0x8a, 0x99, 0x08, 0x9c, 0x56,
	0xf2, 0x04, 0x6a, 0xc7, 0x8c, 0xf7, 0x27, 0x72, 0x91, 0x46, 0x0c, 0x90, 0xa2, 0x7b, 0x1a, 0xd4,
	0x67, 0x58, 0x3e, 0x60, 0xfe, 0x05, 0xe5, 0x5e, 0x8c, 0xb5, 0x15, 0x63, 0x3d, 0x06, 0xe8, 0x18,
	0x56, 0x43, 0x20, 0xcd, 0x1f, 0xd7, 0xef, 0xd1, 0x98, 0x5c, 0x6c, 0x5a, 0xff, 0x34, 0x9c, 0x53,
	0x58, 0x99, 0x5d, 0xc7, 0x89, 0xee, 0x52, 0x36, 0x75, 0x7a, 0x77, 0xb5, 0xe9, 0x1d, 0x4d, 0xb6,
	0x63, 0xa8, 0xb9, 0xcb, 0x3b, 0x0d, 0xa8, 0x03, 0x95, 0xc4, 0xc2, 0x26, 0x9b, 0x33, 0x28, 0xc9,
	0x9d, 0x7c, 0x07, 0x44, 0x62, 0x81, 0x27, 0x20, 0x6e, 0xaf, 0xf5, 0x34, 0x88, 0x7d, 0x28, 0x45,
	0xd3, 0x3f, 0x3b, 0x9c, 0x4f, 0x63, 0x73, 0xf6, 0x7d, 0x98, 0x0b, 0xe4, 0x4d, 0x54, 0x5a, 0xa7,
	0xd6, 0xe2, 0x58, 0x65, 0xa7, 0x55, 0xfb, 0x08, 0xeb, 0x3a, 0xab, 0xe3, 0xbb, 0x16, 0x5e, 0x70,
	0x14, 0x97, 0x8f, 0xca, 0x7f, 0x0b, 0xd5, 0xff, 0x48, 0xeb, 0x16, 0x94, 0xf9, 0xfa, 0x5f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x32, 0xe2, 0xef, 0x64, 0xd6, 0x07, 0x00, 0x00,
}
