// Code generated by "stringer -type RequestType"; DO NOT EDIT.

package hub

import "strconv"

const _RequestType_name = "AddTaskTaskListCancelTask"

var _RequestType_index = [...]uint8{0, 7, 15, 25}

func (i RequestType) String() string {
	if i < 0 || i >= RequestType(len(_RequestType_index)-1) {
		return "RequestType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RequestType_name[_RequestType_index[i]:_RequestType_index[i+1]]
}
