// Code generated by "stringer -type TaskStatus"; DO NOT EDIT.

package hub

import "strconv"

const _TaskStatus_name = "NewRunningStartFailedUpdatingUpdateFailedCancelledDone"

var _TaskStatus_index = [...]uint8{0, 3, 10, 21, 29, 41, 50, 54}

func (i TaskStatus) String() string {
	if i < 0 || i >= TaskStatus(len(_TaskStatus_index)-1) {
		return "TaskStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TaskStatus_name[_TaskStatus_index[i]:_TaskStatus_index[i+1]]
}
