// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/k8s/dccnk8s.proto

package k8s

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_dccnk8s_d6634b8a93d90001, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type CommonRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonRequest) Reset()         { *m = CommonRequest{} }
func (m *CommonRequest) String() string { return proto.CompactTextString(m) }
func (*CommonRequest) ProtoMessage()    {}
func (*CommonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dccnk8s_d6634b8a93d90001, []int{1}
}
func (m *CommonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonRequest.Unmarshal(m, b)
}
func (m *CommonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonRequest.Marshal(b, m, deterministic)
}
func (dst *CommonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonRequest.Merge(dst, src)
}
func (m *CommonRequest) XXX_Size() int {
	return xxx_messageInfo_CommonRequest.Size(m)
}
func (m *CommonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommonRequest proto.InternalMessageInfo

type CommonResponce struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonResponce) Reset()         { *m = CommonResponce{} }
func (m *CommonResponce) String() string { return proto.CompactTextString(m) }
func (*CommonResponce) ProtoMessage()    {}
func (*CommonResponce) Descriptor() ([]byte, []int) {
	return fileDescriptor_dccnk8s_d6634b8a93d90001, []int{2}
}
func (m *CommonResponce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonResponce.Unmarshal(m, b)
}
func (m *CommonResponce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonResponce.Marshal(b, m, deterministic)
}
func (dst *CommonResponce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonResponce.Merge(dst, src)
}
func (m *CommonResponce) XXX_Size() int {
	return xxx_messageInfo_CommonResponce.Size(m)
}
func (m *CommonResponce) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonResponce.DiscardUnknown(m)
}

var xxx_messageInfo_CommonResponce proto.InternalMessageInfo

type NewTaskRequest struct {
	Common               *CommonRequest `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Type                 string         `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Taskid               int64          `protobuf:"varint,3,opt,name=taskid,proto3" json:"taskid,omitempty"`
	TaskType             string         `protobuf:"bytes,4,opt,name=taskType,proto3" json:"taskType,omitempty"`
	Name                 string         `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Image                string         `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Replica              int64          `protobuf:"varint,7,opt,name=replica,proto3" json:"replica,omitempty"`
	Extra                string         `protobuf:"bytes,8,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NewTaskRequest) Reset()         { *m = NewTaskRequest{} }
func (m *NewTaskRequest) String() string { return proto.CompactTextString(m) }
func (*NewTaskRequest) ProtoMessage()    {}
func (*NewTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dccnk8s_d6634b8a93d90001, []int{3}
}
func (m *NewTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTaskRequest.Unmarshal(m, b)
}
func (m *NewTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTaskRequest.Marshal(b, m, deterministic)
}
func (dst *NewTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTaskRequest.Merge(dst, src)
}
func (m *NewTaskRequest) XXX_Size() int {
	return xxx_messageInfo_NewTaskRequest.Size(m)
}
func (m *NewTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewTaskRequest proto.InternalMessageInfo

func (m *NewTaskRequest) GetCommon() *CommonRequest {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *NewTaskRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *NewTaskRequest) GetTaskid() int64 {
	if m != nil {
		return m.Taskid
	}
	return 0
}

func (m *NewTaskRequest) GetTaskType() string {
	if m != nil {
		return m.TaskType
	}
	return ""
}

func (m *NewTaskRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewTaskRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *NewTaskRequest) GetReplica() int64 {
	if m != nil {
		return m.Replica
	}
	return 0
}

func (m *NewTaskRequest) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

type NewTaskResponce struct {
	Common               *CommonResponce `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Type                 string          `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Taskid               int64           `protobuf:"varint,3,opt,name=taskid,proto3" json:"taskid,omitempty"`
	Taskname             string          `protobuf:"bytes,4,opt,name=taskname,proto3" json:"taskname,omitempty"`
	Status               string          `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Datacenter           string          `protobuf:"bytes,6,opt,name=datacenter,proto3" json:"datacenter,omitempty"`
	Url                  string          `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	Report               string          `protobuf:"bytes,8,opt,name=report,proto3" json:"report,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NewTaskResponce) Reset()         { *m = NewTaskResponce{} }
func (m *NewTaskResponce) String() string { return proto.CompactTextString(m) }
func (*NewTaskResponce) ProtoMessage()    {}
func (*NewTaskResponce) Descriptor() ([]byte, []int) {
	return fileDescriptor_dccnk8s_d6634b8a93d90001, []int{4}
}
func (m *NewTaskResponce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTaskResponce.Unmarshal(m, b)
}
func (m *NewTaskResponce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTaskResponce.Marshal(b, m, deterministic)
}
func (dst *NewTaskResponce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTaskResponce.Merge(dst, src)
}
func (m *NewTaskResponce) XXX_Size() int {
	return xxx_messageInfo_NewTaskResponce.Size(m)
}
func (m *NewTaskResponce) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTaskResponce.DiscardUnknown(m)
}

var xxx_messageInfo_NewTaskResponce proto.InternalMessageInfo

func (m *NewTaskResponce) GetCommon() *CommonResponce {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *NewTaskResponce) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *NewTaskResponce) GetTaskid() int64 {
	if m != nil {
		return m.Taskid
	}
	return 0
}

func (m *NewTaskResponce) GetTaskname() string {
	if m != nil {
		return m.Taskname
	}
	return ""
}

func (m *NewTaskResponce) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *NewTaskResponce) GetDatacenter() string {
	if m != nil {
		return m.Datacenter
	}
	return ""
}

func (m *NewTaskResponce) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *NewTaskResponce) GetReport() string {
	if m != nil {
		return m.Report
	}
	return ""
}

type UpdateTaskRequest struct {
	Common               *CommonRequest `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Type                 string         `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Taskid               int64          `protobuf:"varint,3,opt,name=taskid,proto3" json:"taskid,omitempty"`
	TaskType             string         `protobuf:"bytes,4,opt,name=taskType,proto3" json:"taskType,omitempty"`
	Name                 string         `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Image                string         `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Replica              int64          `protobuf:"varint,7,opt,name=replica,proto3" json:"replica,omitempty"`
	Extra                string         `protobuf:"bytes,8,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateTaskRequest) Reset()         { *m = UpdateTaskRequest{} }
func (m *UpdateTaskRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskRequest) ProtoMessage()    {}
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dccnk8s_d6634b8a93d90001, []int{5}
}
func (m *UpdateTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskRequest.Unmarshal(m, b)
}
func (m *UpdateTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskRequest.Merge(dst, src)
}
func (m *UpdateTaskRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskRequest.Size(m)
}
func (m *UpdateTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskRequest proto.InternalMessageInfo

func (m *UpdateTaskRequest) GetCommon() *CommonRequest {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *UpdateTaskRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *UpdateTaskRequest) GetTaskid() int64 {
	if m != nil {
		return m.Taskid
	}
	return 0
}

func (m *UpdateTaskRequest) GetTaskType() string {
	if m != nil {
		return m.TaskType
	}
	return ""
}

func (m *UpdateTaskRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateTaskRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *UpdateTaskRequest) GetReplica() int64 {
	if m != nil {
		return m.Replica
	}
	return 0
}

func (m *UpdateTaskRequest) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

type UpdateTaskResponce struct {
	Common               *CommonResponce `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Type                 string          `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Taskid               int64           `protobuf:"varint,3,opt,name=taskid,proto3" json:"taskid,omitempty"`
	Taskname             string          `protobuf:"bytes,4,opt,name=taskname,proto3" json:"taskname,omitempty"`
	Status               string          `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Datacenter           string          `protobuf:"bytes,6,opt,name=datacenter,proto3" json:"datacenter,omitempty"`
	Url                  string          `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	Report               string          `protobuf:"bytes,8,opt,name=report,proto3" json:"report,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateTaskResponce) Reset()         { *m = UpdateTaskResponce{} }
func (m *UpdateTaskResponce) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskResponce) ProtoMessage()    {}
func (*UpdateTaskResponce) Descriptor() ([]byte, []int) {
	return fileDescriptor_dccnk8s_d6634b8a93d90001, []int{6}
}
func (m *UpdateTaskResponce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskResponce.Unmarshal(m, b)
}
func (m *UpdateTaskResponce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskResponce.Marshal(b, m, deterministic)
}
func (dst *UpdateTaskResponce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskResponce.Merge(dst, src)
}
func (m *UpdateTaskResponce) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskResponce.Size(m)
}
func (m *UpdateTaskResponce) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskResponce.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskResponce proto.InternalMessageInfo

func (m *UpdateTaskResponce) GetCommon() *CommonResponce {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *UpdateTaskResponce) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *UpdateTaskResponce) GetTaskid() int64 {
	if m != nil {
		return m.Taskid
	}
	return 0
}

func (m *UpdateTaskResponce) GetTaskname() string {
	if m != nil {
		return m.Taskname
	}
	return ""
}

func (m *UpdateTaskResponce) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UpdateTaskResponce) GetDatacenter() string {
	if m != nil {
		return m.Datacenter
	}
	return ""
}

func (m *UpdateTaskResponce) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *UpdateTaskResponce) GetReport() string {
	if m != nil {
		return m.Report
	}
	return ""
}

type CancelTaskRequest struct {
	Common               *CommonRequest `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Type                 string         `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Taskid               int64          `protobuf:"varint,3,opt,name=taskid,proto3" json:"taskid,omitempty"`
	TaskType             string         `protobuf:"bytes,4,opt,name=taskType,proto3" json:"taskType,omitempty"`
	Name                 string         `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Image                string         `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Replica              int64          `protobuf:"varint,7,opt,name=replica,proto3" json:"replica,omitempty"`
	Extra                string         `protobuf:"bytes,8,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CancelTaskRequest) Reset()         { *m = CancelTaskRequest{} }
func (m *CancelTaskRequest) String() string { return proto.CompactTextString(m) }
func (*CancelTaskRequest) ProtoMessage()    {}
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dccnk8s_d6634b8a93d90001, []int{7}
}
func (m *CancelTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelTaskRequest.Unmarshal(m, b)
}
func (m *CancelTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelTaskRequest.Marshal(b, m, deterministic)
}
func (dst *CancelTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelTaskRequest.Merge(dst, src)
}
func (m *CancelTaskRequest) XXX_Size() int {
	return xxx_messageInfo_CancelTaskRequest.Size(m)
}
func (m *CancelTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelTaskRequest proto.InternalMessageInfo

func (m *CancelTaskRequest) GetCommon() *CommonRequest {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *CancelTaskRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CancelTaskRequest) GetTaskid() int64 {
	if m != nil {
		return m.Taskid
	}
	return 0
}

func (m *CancelTaskRequest) GetTaskType() string {
	if m != nil {
		return m.TaskType
	}
	return ""
}

func (m *CancelTaskRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CancelTaskRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *CancelTaskRequest) GetReplica() int64 {
	if m != nil {
		return m.Replica
	}
	return 0
}

func (m *CancelTaskRequest) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

type CancelTaskResponce struct {
	Common               *CommonResponce `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Type                 string          `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Taskid               int64           `protobuf:"varint,3,opt,name=taskid,proto3" json:"taskid,omitempty"`
	Taskname             string          `protobuf:"bytes,4,opt,name=taskname,proto3" json:"taskname,omitempty"`
	Status               string          `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Datacenter           string          `protobuf:"bytes,6,opt,name=datacenter,proto3" json:"datacenter,omitempty"`
	Url                  string          `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	Report               string          `protobuf:"bytes,8,opt,name=report,proto3" json:"report,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CancelTaskResponce) Reset()         { *m = CancelTaskResponce{} }
func (m *CancelTaskResponce) String() string { return proto.CompactTextString(m) }
func (*CancelTaskResponce) ProtoMessage()    {}
func (*CancelTaskResponce) Descriptor() ([]byte, []int) {
	return fileDescriptor_dccnk8s_d6634b8a93d90001, []int{8}
}
func (m *CancelTaskResponce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelTaskResponce.Unmarshal(m, b)
}
func (m *CancelTaskResponce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelTaskResponce.Marshal(b, m, deterministic)
}
func (dst *CancelTaskResponce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelTaskResponce.Merge(dst, src)
}
func (m *CancelTaskResponce) XXX_Size() int {
	return xxx_messageInfo_CancelTaskResponce.Size(m)
}
func (m *CancelTaskResponce) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelTaskResponce.DiscardUnknown(m)
}

var xxx_messageInfo_CancelTaskResponce proto.InternalMessageInfo

func (m *CancelTaskResponce) GetCommon() *CommonResponce {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *CancelTaskResponce) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CancelTaskResponce) GetTaskid() int64 {
	if m != nil {
		return m.Taskid
	}
	return 0
}

func (m *CancelTaskResponce) GetTaskname() string {
	if m != nil {
		return m.Taskname
	}
	return ""
}

func (m *CancelTaskResponce) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CancelTaskResponce) GetDatacenter() string {
	if m != nil {
		return m.Datacenter
	}
	return ""
}

func (m *CancelTaskResponce) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CancelTaskResponce) GetReport() string {
	if m != nil {
		return m.Report
	}
	return ""
}

type HeartBeatRequest struct {
	Common               *CommonRequest `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Type                 string         `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Taskid               int64          `protobuf:"varint,3,opt,name=taskid,proto3" json:"taskid,omitempty"`
	TaskType             string         `protobuf:"bytes,4,opt,name=taskType,proto3" json:"taskType,omitempty"`
	Name                 string         `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Image                string         `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Replica              int64          `protobuf:"varint,7,opt,name=replica,proto3" json:"replica,omitempty"`
	Extra                string         `protobuf:"bytes,8,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *HeartBeatRequest) Reset()         { *m = HeartBeatRequest{} }
func (m *HeartBeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartBeatRequest) ProtoMessage()    {}
func (*HeartBeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dccnk8s_d6634b8a93d90001, []int{9}
}
func (m *HeartBeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatRequest.Unmarshal(m, b)
}
func (m *HeartBeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatRequest.Marshal(b, m, deterministic)
}
func (dst *HeartBeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatRequest.Merge(dst, src)
}
func (m *HeartBeatRequest) XXX_Size() int {
	return xxx_messageInfo_HeartBeatRequest.Size(m)
}
func (m *HeartBeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatRequest proto.InternalMessageInfo

func (m *HeartBeatRequest) GetCommon() *CommonRequest {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *HeartBeatRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *HeartBeatRequest) GetTaskid() int64 {
	if m != nil {
		return m.Taskid
	}
	return 0
}

func (m *HeartBeatRequest) GetTaskType() string {
	if m != nil {
		return m.TaskType
	}
	return ""
}

func (m *HeartBeatRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HeartBeatRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *HeartBeatRequest) GetReplica() int64 {
	if m != nil {
		return m.Replica
	}
	return 0
}

func (m *HeartBeatRequest) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

type HeartBeatResponce struct {
	Common               *CommonResponce `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Type                 string          `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Taskid               int64           `protobuf:"varint,3,opt,name=taskid,proto3" json:"taskid,omitempty"`
	Taskname             string          `protobuf:"bytes,4,opt,name=taskname,proto3" json:"taskname,omitempty"`
	Status               string          `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Datacenter           string          `protobuf:"bytes,6,opt,name=datacenter,proto3" json:"datacenter,omitempty"`
	Url                  string          `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	Report               string          `protobuf:"bytes,8,opt,name=report,proto3" json:"report,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *HeartBeatResponce) Reset()         { *m = HeartBeatResponce{} }
func (m *HeartBeatResponce) String() string { return proto.CompactTextString(m) }
func (*HeartBeatResponce) ProtoMessage()    {}
func (*HeartBeatResponce) Descriptor() ([]byte, []int) {
	return fileDescriptor_dccnk8s_d6634b8a93d90001, []int{10}
}
func (m *HeartBeatResponce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatResponce.Unmarshal(m, b)
}
func (m *HeartBeatResponce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatResponce.Marshal(b, m, deterministic)
}
func (dst *HeartBeatResponce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatResponce.Merge(dst, src)
}
func (m *HeartBeatResponce) XXX_Size() int {
	return xxx_messageInfo_HeartBeatResponce.Size(m)
}
func (m *HeartBeatResponce) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatResponce.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatResponce proto.InternalMessageInfo

func (m *HeartBeatResponce) GetCommon() *CommonResponce {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *HeartBeatResponce) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *HeartBeatResponce) GetTaskid() int64 {
	if m != nil {
		return m.Taskid
	}
	return 0
}

func (m *HeartBeatResponce) GetTaskname() string {
	if m != nil {
		return m.Taskname
	}
	return ""
}

func (m *HeartBeatResponce) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *HeartBeatResponce) GetDatacenter() string {
	if m != nil {
		return m.Datacenter
	}
	return ""
}

func (m *HeartBeatResponce) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *HeartBeatResponce) GetReport() string {
	if m != nil {
		return m.Report
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "k8s.Empty")
	proto.RegisterType((*CommonRequest)(nil), "k8s.CommonRequest")
	proto.RegisterType((*CommonResponce)(nil), "k8s.CommonResponce")
	proto.RegisterType((*NewTaskRequest)(nil), "k8s.NewTaskRequest")
	proto.RegisterType((*NewTaskResponce)(nil), "k8s.NewTaskResponce")
	proto.RegisterType((*UpdateTaskRequest)(nil), "k8s.UpdateTaskRequest")
	proto.RegisterType((*UpdateTaskResponce)(nil), "k8s.UpdateTaskResponce")
	proto.RegisterType((*CancelTaskRequest)(nil), "k8s.CancelTaskRequest")
	proto.RegisterType((*CancelTaskResponce)(nil), "k8s.CancelTaskResponce")
	proto.RegisterType((*HeartBeatRequest)(nil), "k8s.HeartBeatRequest")
	proto.RegisterType((*HeartBeatResponce)(nil), "k8s.HeartBeatResponce")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Dccnk8SClient is the client API for Dccnk8S service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type Dccnk8SClient interface {
	NewTask(ctx context.Context, in *NewTaskRequest, opts ...grpc.CallOption) (*NewTaskResponce, error)
	UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*UpdateTaskResponce, error)
	CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponce, error)
	HeartBeat(ctx context.Context, in *HeartBeatRequest, opts ...grpc.CallOption) (*HeartBeatResponce, error)
}

type dccnk8SClient struct {
	cc *grpc.ClientConn
}

func NewDccnk8SClient(cc *grpc.ClientConn) Dccnk8SClient {
	return &dccnk8SClient{cc}
}

func (c *dccnk8SClient) NewTask(ctx context.Context, in *NewTaskRequest, opts ...grpc.CallOption) (*NewTaskResponce, error) {
	out := new(NewTaskResponce)
	err := c.cc.Invoke(ctx, "/k8s.dccnk8s/NewTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dccnk8SClient) UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*UpdateTaskResponce, error) {
	out := new(UpdateTaskResponce)
	err := c.cc.Invoke(ctx, "/k8s.dccnk8s/UpdateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dccnk8SClient) CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponce, error) {
	out := new(CancelTaskResponce)
	err := c.cc.Invoke(ctx, "/k8s.dccnk8s/CancelTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dccnk8SClient) HeartBeat(ctx context.Context, in *HeartBeatRequest, opts ...grpc.CallOption) (*HeartBeatResponce, error) {
	out := new(HeartBeatResponce)
	err := c.cc.Invoke(ctx, "/k8s.dccnk8s/HeartBeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Dccnk8SServer is the server API for Dccnk8S service.
type Dccnk8SServer interface {
	NewTask(context.Context, *NewTaskRequest) (*NewTaskResponce, error)
	UpdateTask(context.Context, *UpdateTaskRequest) (*UpdateTaskResponce, error)
	CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponce, error)
	HeartBeat(context.Context, *HeartBeatRequest) (*HeartBeatResponce, error)
}

func RegisterDccnk8SServer(s *grpc.Server, srv Dccnk8SServer) {
	s.RegisterService(&_Dccnk8S_serviceDesc, srv)
}

func _Dccnk8S_NewTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Dccnk8SServer).NewTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/k8s.dccnk8s/NewTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Dccnk8SServer).NewTask(ctx, req.(*NewTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dccnk8S_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Dccnk8SServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/k8s.dccnk8s/UpdateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Dccnk8SServer).UpdateTask(ctx, req.(*UpdateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dccnk8S_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Dccnk8SServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/k8s.dccnk8s/CancelTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Dccnk8SServer).CancelTask(ctx, req.(*CancelTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dccnk8S_HeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartBeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Dccnk8SServer).HeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/k8s.dccnk8s/HeartBeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Dccnk8SServer).HeartBeat(ctx, req.(*HeartBeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dccnk8S_serviceDesc = grpc.ServiceDesc{
	ServiceName: "k8s.dccnk8s",
	HandlerType: (*Dccnk8SServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewTask",
			Handler:    _Dccnk8S_NewTask_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _Dccnk8S_UpdateTask_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _Dccnk8S_CancelTask_Handler,
		},
		{
			MethodName: "HeartBeat",
			Handler:    _Dccnk8S_HeartBeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocol/k8s/dccnk8s.proto",
}

func init() { proto.RegisterFile("protocol/k8s/dccnk8s.proto", fileDescriptor_dccnk8s_d6634b8a93d90001) }

var fileDescriptor_dccnk8s_d6634b8a93d90001 = []byte{
	// 438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x96, 0x4f, 0x8b, 0xd3, 0x40,
	0x18, 0xc6, 0x77, 0x36, 0xdb, 0x64, 0xfb, 0x8a, 0xbb, 0xdd, 0xd7, 0x35, 0x0e, 0x39, 0x48, 0xc9,
	0xa9, 0x28, 0xec, 0xc2, 0x0a, 0xd2, 0x83, 0x20, 0xb8, 0x08, 0x9e, 0x3c, 0x84, 0xfa, 0x01, 0xc6,
	0xc9, 0x8b, 0x94, 0xfc, 0x75, 0x66, 0x8a, 0xf6, 0xe8, 0x17, 0x15, 0xbd, 0x89, 0x7e, 0x09, 0xc9,
	0x64, 0xda, 0x26, 0xcd, 0x71, 0x6f, 0xb9, 0xcd, 0xfb, 0xf0, 0xf4, 0x81, 0x1f, 0x4f, 0x67, 0xde,
	0x40, 0x54, 0xab, 0xca, 0x54, 0xb2, 0xca, 0x6f, 0xb3, 0xa5, 0xbe, 0x4d, 0xa5, 0x2c, 0xb3, 0xa5,
	0xbe, 0xb1, 0x22, 0x7a, 0xd9, 0x52, 0xc7, 0x01, 0x4c, 0xde, 0x17, 0xb5, 0xd9, 0xc6, 0x97, 0xf0,
	0xf8, 0xbe, 0x2a, 0x8a, 0xaa, 0x4c, 0xe8, 0xeb, 0x86, 0xb4, 0x89, 0x67, 0x70, 0xb1, 0x13, 0x74,
	0x5d, 0x95, 0x92, 0xe2, 0x9f, 0x0c, 0x2e, 0x3e, 0xd2, 0xb7, 0x95, 0xd0, 0x99, 0x33, 0xe1, 0x0b,
	0xf0, 0xa5, 0x35, 0x71, 0x36, 0x67, 0x8b, 0x47, 0x77, 0x78, 0xd3, 0xe4, 0xf7, 0x82, 0x12, 0xe7,
	0x40, 0x84, 0xb3, 0xd5, 0xb6, 0x26, 0x7e, 0x3a, 0x67, 0x8b, 0x69, 0x62, 0xcf, 0x18, 0x82, 0x6f,
	0x84, 0xce, 0xd6, 0x29, 0xf7, 0xe6, 0x6c, 0xe1, 0x25, 0x6e, 0xc2, 0x08, 0xce, 0x9b, 0x93, 0xf5,
	0x9f, 0x59, 0xff, 0x7e, 0x6e, 0x72, 0x4a, 0x51, 0x10, 0x9f, 0xb4, 0x39, 0xcd, 0x19, 0xaf, 0x61,
	0xb2, 0x2e, 0xc4, 0x17, 0xe2, 0xbe, 0x15, 0xdb, 0x01, 0x39, 0x04, 0x8a, 0xea, 0x7c, 0x2d, 0x05,
	0x0f, 0x6c, 0xfc, 0x6e, 0x6c, 0xfc, 0xf4, 0xdd, 0x28, 0xc1, 0xcf, 0x5b, 0xbf, 0x1d, 0xe2, 0x3f,
	0x0c, 0x2e, 0xf7, 0x80, 0x2d, 0x34, 0xbe, 0x3c, 0x22, 0x7c, 0xd2, 0x23, 0x6c, 0x4d, 0x0f, 0x41,
	0xb4, 0x28, 0x1d, 0x44, 0x8b, 0x13, 0x82, 0xaf, 0x8d, 0x30, 0x1b, 0xed, 0x20, 0xdd, 0x84, 0xcf,
	0x01, 0x52, 0x61, 0x84, 0xa4, 0xd2, 0x90, 0x72, 0xac, 0x1d, 0x05, 0x67, 0xe0, 0x6d, 0x54, 0x6e,
	0x61, 0xa7, 0x49, 0x73, 0x6c, 0x92, 0x14, 0xd5, 0x95, 0x32, 0x8e, 0xd4, 0x4d, 0xf1, 0x6f, 0x06,
	0x57, 0x9f, 0xea, 0x54, 0x18, 0x1a, 0x6f, 0x9d, 0xff, 0x18, 0x60, 0x97, 0x71, 0xfc, 0x8d, 0xde,
	0x8b, 0x52, 0x52, 0x3e, 0xee, 0x46, 0xbb, 0x8c, 0xe3, 0x6e, 0xf4, 0x17, 0x83, 0xd9, 0x07, 0x12,
	0xca, 0xbc, 0x23, 0x61, 0xc6, 0x59, 0xe8, 0x5f, 0x06, 0x57, 0x1d, 0xc4, 0x51, 0xf7, 0x79, 0xf7,
	0xe3, 0x14, 0x02, 0xb7, 0x82, 0xf1, 0x35, 0x04, 0x6e, 0xd3, 0x60, 0x4b, 0xd7, 0x5f, 0xac, 0xd1,
	0x75, 0x5f, 0x74, 0x1b, 0xf8, 0x04, 0xdf, 0x02, 0x1c, 0x9e, 0x34, 0x0c, 0xad, 0x6b, 0xf0, 0x8e,
	0x47, 0xcf, 0x06, 0x7a, 0x37, 0xe0, 0x70, 0x83, 0x5c, 0xc0, 0xe0, 0xd9, 0x70, 0x01, 0xc3, 0xab,
	0x16, 0x9f, 0xe0, 0x1b, 0x98, 0xee, 0x1b, 0xc3, 0xa7, 0xd6, 0x77, 0xfc, 0x27, 0x8d, 0xc2, 0x63,
	0x79, 0xf7, 0xeb, 0xcf, 0xbe, 0xfd, 0xf6, 0x78, 0xf5, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x40, 0x14,
	0xbe, 0x5e, 0x99, 0x08, 0x00, 0x00,
}
