// Code generated by "stringer -type DataCennterTaskStatus"; DO NOT EDIT.

package dc

import "strconv"

const _DataCennterTaskStatus_name = "StartSuccessStartFailureUpdateSuccessUpdateFailureDoneCancelled"

var _DataCennterTaskStatus_index = [...]uint8{0, 12, 24, 37, 50, 54, 63}

func (i DataCennterTaskStatus) String() string {
	if i < 0 || i >= DataCennterTaskStatus(len(_DataCennterTaskStatus_index)-1) {
		return "DataCennterTaskStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataCennterTaskStatus_name[_DataCennterTaskStatus_index[i]:_DataCennterTaskStatus_index[i+1]]
}
