// Code generated by "stringer -type DataCenteStatus"; DO NOT EDIT.

package dc

import "strconv"

const _DataCenteStatus_name = "OnlineOffline"

var _DataCenteStatus_index = [...]uint8{0, 6, 13}

func (i DataCenteStatus) String() string {
	if i < 0 || i >= DataCenteStatus(len(_DataCenteStatus_index)-1) {
		return "DataCenteStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataCenteStatus_name[_DataCenteStatus_index[i]:_DataCenteStatus_index[i+1]]
}
